version: '3'

services:
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password123
    volumes:
      - .postgres-data:/var/lib/postgresql/data
    ports:
      - 8080:5432